-- Blog schema column parity migration
-- Additive only — safe for production

ALTER TABLE "BlogPost"
ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'draft',
ADD COLUMN IF NOT EXISTS "authorId" TEXT,
ADD COLUMN IF NOT EXISTS "authorName" TEXT,
ADD COLUMN IF NOT EXISTS "submittedAt" TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS "approvedAt" TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS "publishedAt" TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();