-- CREATE TABLE "CommunityPost" (
--   "id" TEXT NOT NULL,
--   "authorId" TEXT NOT NULL,
--   "roomId" TEXT,
--   "content" TEXT NOT NULL,
--   "sourceType" TEXT,
--   "sourcePrompt" TEXT,
--   "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

--   CONSTRAINT "CommunityPost_pkey" PRIMARY KEY ("id")
-- );
-- No-op migration (CommunityPost already exists)